image: elixir:latest

variables:
  MIX_ENV: "test"

before_script:
  stage: prepare
  ## Install ssh-agent if not already installed, it is required by Docker.
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

deps:
  stage: get_deps
  script:
    - make deps

common_tests:
  stage: common_tests
  script:
    - make test    

dyalize:
  stage: dyalize
  script:
    - make dyalizer
