image: erlang:24-alpine

variables:
  MIX_ENV: "test"

before_script:
  ## Install ssh-agent if not already installed, it is required by Docker.
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

deps-get:
  stage: .pre
  script:
    - make deps

build:
  stage: build
  script:
    - make build

tests-common:
  stage: test
  script:
    - make test    

linting-dyalize:
  stage: test
  script:
    - make dyalizer
