pipelines:
  branches:
    master:
    - step:
        image: elixir
        
        script:
          - apt-get update
          - apt-get install -y build-essential cmake erlang
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - mix test
 
definitions:
  caches:
    deps: deps
    build: _build 