pipelines:
  branches:
    master:
    - step:
        image: elixir:1.5
        caches:
          - deps
          - build
        script:
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - mix test
 
definitions:
  caches:
    deps: deps
    build: _build 